#!/bin/bash 
#SBATCH -J water_train         
#SBATCH -n 128        
#SBATCH -N 1 
#SBATCH -p normal     
#SBATCH -t 48:00:00        

module load tacc-singularity
mpirun -np 4 singularity run /work/08039/cxliang/ls6/DPMD bash train.sh
