#!/bin/bash 
#SBATCH -J set_bulk         
#SBATCH -n 100         
#SBATCH -N 1 
#SBATCH -p development     
#SBATCH -t 1:00:00        

module load tacc-singularity
singularity run /work/08039/cxliang/ls6/DPMD dp neighbor-stat -s ./train_set -r 6.00 -t O H
